version: 1.0.{build}
image: Visual Studio 2017
clone_folder: C:\CodePulse
build_script:
- cmd: powershell -file C:\CodePulse\installers\build.ps1
test:
  assemblies:
    only:
    - '**\CodePulse.Client.Test.dll'
artifacts:
- path: installers\Windows\CodePulse.Bundle.Windows\bin\Release\CodePulse.Windows.exe
  name: CodePulse.Windows.exe (Release)