version: 1.0.{build}
image: Visual Studio 2017
clone_folder: C:\CodePulse
build_script:
- cmd: powershell -file C:\CodePulse\installers\build.ps1 -version %APPVEYOR_BUILD_VERSION%
before_test:
- cmd: >-
    C:\Windows\System32\regsvr32.exe C:\CodePulse\dotnet-tracer\main\bin\Release\x64\OpenCover.Profiler.dll /s

    C:\Windows\SysWOW64\regsvr32.exe C:\CodePulse\dotnet-tracer\main\bin\Release\x86\OpenCover.Profiler.dll /s
test:
  assemblies:
    only:
    - '**\CodePulse.Client.Test.dll'
    - '**\CodePulse.Console.Test.dll'
    - '**\OpenCover.Test.dll'
    - '**\OpenCover.Test.Profiler.dll'
after_test:
- ps: >-
    $wc = New-Object 'System.Net.WebClient'


    C:\CodePulse\dotnet-tracer\main\bin\Release\x86\OpenCover.Test.Profiler.exe --gtest_output="xml:C:\CodePulse\OpenCover.Test.Profiler.x86.xml" --gtest_filter=-TimerTest*

    $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", "C:\CodePulse\OpenCover.Test.Profiler.x86.xml")


    C:\CodePulse\dotnet-tracer\main\bin\Release\x64\OpenCover.Test.Profiler.exe --gtest_output="xml:C:\CodePulse\OpenCover.Test.Profiler.x64.xml" --gtest_filter=-TimerTest*

    $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", "C:\CodePulse\OpenCover.Test.Profiler.x64.xml")
artifacts:
- path: installers\Windows\CodePulse.Installer.Win64\bin\Release\CodePulse.Win64.msi
  name: CodePulse.Win64.msi (Release)